* Encoding: UTF-8.
ONEWAY likeCount BY post_type 
  /STATISTICS DESCRIPTIVES 
  /PLOT MEANS 
  /MISSING ANALYSIS.

ONEWAY commentCount BY post_type 
  /STATISTICS DESCRIPTIVES 
  /PLOT MEANS 
  /MISSING ANALYSIS.

* Curve Estimation. 
TSET NEWVAR=NONE. 
CURVEFIT 
  /VARIABLES=likeCount WITH wordcount 
  /CONSTANT 
  /MODEL=LINEAR LOGARITHMIC INVERSE QUADRATIC CUBIC COMPOUND POWER S GROWTH EXPONENTIAL 
  /PRINT ANOVA 
  /PLOT FIT.

* Curve Estimation. 
TSET NEWVAR=NONE. 
CURVEFIT 
  /VARIABLES=commentCount WITH wordcount 
  /CONSTANT 
  /MODEL=LINEAR LOGARITHMIC INVERSE QUADRATIC CUBIC COMPOUND POWER S GROWTH EXPONENTIAL 
  /PRINT ANOVA 
  /PLOT FIT.

* Curve Estimation. 
TSET NEWVAR=NONE. 
CURVEFIT 
  /VARIABLES=likeCount WITH SMOG 
  /CONSTANT 
  /MODEL=LINEAR LOGARITHMIC INVERSE QUADRATIC CUBIC COMPOUND POWER S GROWTH EXPONENTIAL 
  /PRINT ANOVA 
  /PLOT FIT.

* Curve Estimation. 
TSET NEWVAR=NONE. 
CURVEFIT 
  /VARIABLES=commentCount WITH SMOG 
  /CONSTANT 
  /MODEL=LINEAR LOGARITHMIC INVERSE QUADRATIC CUBIC COMPOUND POWER S GROWTH EXPONENTIAL 
  /PRINT ANOVA 
  /PLOT FIT.

* Curve Estimation. 
TSET NEWVAR=NONE. 
CURVEFIT 
  /VARIABLES=likeCount WITH FleschKincaidGradeLevel 
  /CONSTANT 
  /MODEL=LINEAR LOGARITHMIC INVERSE QUADRATIC CUBIC COMPOUND POWER S GROWTH EXPONENTIAL 
  /PRINT ANOVA 
  /PLOT FIT.

* Curve Estimation. 
TSET NEWVAR=NONE. 
CURVEFIT 
  /VARIABLES=commentCount WITH FleschKincaidGradeLevel 
  /CONSTANT 
  /MODEL=LINEAR LOGARITHMIC INVERSE QUADRATIC CUBIC COMPOUND POWER S GROWTH EXPONENTIAL 
  /PRINT ANOVA 
  /PLOT FIT.

* Curve Estimation. 
TSET NEWVAR=NONE. 
CURVEFIT 
  /VARIABLES=likeCount WITH facesno 
  /CONSTANT 
  /MODEL=LINEAR LOGARITHMIC INVERSE QUADRATIC CUBIC COMPOUND POWER S GROWTH EXPONENTIAL 
  /PRINT ANOVA 
  /PLOT FIT.

* Curve Estimation. 
TSET NEWVAR=NONE. 
CURVEFIT 
  /VARIABLES=commentCount WITH facesno 
  /CONSTANT 
  /MODEL=LINEAR LOGARITHMIC INVERSE QUADRATIC CUBIC COMPOUND POWER S GROWTH EXPONENTIAL 
  /PRINT ANOVA 
  /PLOT FIT.

ONEWAY likeCount BY face_existance_in_photo
  /STATISTICS DESCRIPTIVES 
  /PLOT MEANS 
  /MISSING ANALYSIS.

ONEWAY commentCount BY face_existance_in_photo
  /STATISTICS DESCRIPTIVES 
  /PLOT MEANS 
  /MISSING ANALYSIS.

ONEWAY likeCount BY text_existance_in_photo_spss
  /STATISTICS DESCRIPTIVES 
  /PLOT MEANS 
  /MISSING ANALYSIS.

ONEWAY commentCount BY text_existance_in_photo_spss
  /STATISTICS DESCRIPTIVES 
  /PLOT MEANS 
  /MISSING ANALYSIS.

ONEWAY likeCount BY BrandNameinPhotoText 
  /STATISTICS DESCRIPTIVES
  /PLOT MEANS
  /MISSING ANALYSIS.

ONEWAY commentCount BY BrandNameinPhotoText 
  /STATISTICS DESCRIPTIVES
  /PLOT MEANS
  /MISSING ANALYSIS.

* Curve Estimation. 
TSET NEWVAR=NONE. 
CURVEFIT 
  /VARIABLES=likeCount WITH ImageTextWordCount 
  /CONSTANT 
  /MODEL=LINEAR QUADRATIC CUBIC 
  /PRINT ANOVA 
  /PLOT FIT.

* Curve Estimation. 
TSET NEWVAR=NONE. 
CURVEFIT 
  /VARIABLES=commentCount WITH ImageTextWordCount 
  /CONSTANT 
  /MODEL=LINEAR QUADRATIC CUBIC 
  /PRINT ANOVA 
  /PLOT FIT.

ONEWAY likeCount BY html4_color_spss 
  /STATISTICS DESCRIPTIVES
  /PLOT MEANS
  /MISSING ANALYSIS.

ONEWAY commentCount BY  html4_color_spss
  /STATISTICS DESCRIPTIVES
  /PLOT MEANS
  /MISSING ANALYSIS.
