colors = {
    "whitesmoke" : "white",
    "darkslategray" : "gray",
    "darkslateblue" : "blue",
    "silver" : "gray",
    "lavender" : "white",
    "black" : "black",
    "darkgray" : "gray",
    "gainsboro" : "gray",
    "snow" : "white",
    "linen" : "beige",
    "steelblue" : "blue",
    "lightsteelblue" : "blue",
    "dimgray" : "gray",
    "goldenrod" : "orange",
    "darkolivegreen" : "green",
    "midnightblue" : "blue",
    "gray" : "gray",
    "ghostwhite":"white",
    "tan":"brown",
    "dodgerblue":"blue",
    "crimson":"red",
    "rosybrown":"brown",
    "cornflowerblue":"blue",
    "slategray":"gray",
    "yellowgreen":"green",
    "teal":"turquoise",
    "cadetblue":"turquoise",
    "blanchedalmond":"beige",
    "antiquewhite":"beige",
    "darkkhaki":"green",
    "lightgray":"gray",
    "lightslategray":"gray",
    "brown":"brown",
    "thistle":"purple",
    "bisque":"beige",
    "firebrick":"red",
    "aliceblue":"white",
    "indianred":"orange",
    "deeppink":"pink",
    "lightblue":"blue",
    "mintcream":"white",
    "royalblue":"blue",
    "saddlebrown":"brown",
    "sandybrown":"orange",
    "lightseagreen":"green",
    "skyblue":"blue",
    "mediumturquoise":"turquoise",
    "olivedrap":"green",
    "sienna":"brown",
    "darkseagreen":"green",
    "papayawhip":"beige",
    "burlywood":"brown",
    "mediumvioletred":"pink",
    "chocolate":"brown",
    "peru":"brown",
    "darkorange":"orange",
    "gold":"yellow",
    "khaki":""

    }